### ISSUE TITLE
where is the pretrained model?

### ISSUE THREAD

**Issue by anguoyang** [springkim/YOLOv3_SpringEdition#1]
hi @springkim according to the original yolo website, we need to train the v3 from a pretrained model, but I could not found that in your script, there is no such file, is it OK?

**Comment by springkim** [comment]
Hi @anguoyang, You mean weights file for finetune. right? Actually, that finetune model was made by imagenet1K. I tested it before, But, the result is almost same. So i did not use that when i start the train network.
