### ISSUE TITLE
YoloV3 - Little question

### ISSUE THREAD

**Issue by rmiaouh** [springkim/YOLOv3_SpringEdition#8]
I saw the last issues and you did't answered about the : YOLOv3SE_Train.exe.
I cloned it and there is no YOLOv3SE_Train.exe. Can you help us about this please ?

**Comment by springkim** [comment]
Hi @rmiaouh
`YOLOv3SE_Train.exe` is in `build/Release` after build.
You can build as `build_windows_vs2015.bat'.

**Comment by rmiaouh** [comment]
Thk for all :)
